### ISSUE TITLE
Advance Wars 2 - Black Hole Rising (RUS)

### ISSUE THREAD

**Issue by VomBut** [metroid-maniac/gba-flash-patcher#4]
Не работает для Advance Wars 2 - Black Hole Rising (RUS). Предлагает "Are you sure the game has save functionality and has been SRAM patched with GBATA?", но GBATA не помогает

**Comment by metroid-maniac** [comment]
This game already uses the Flash 512K save type. It is not necessary to patch it. This patcher is only for games with SRAM and EEPROM save types.
